[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
FiniteDiff = "6a86dc24-6348-571c-b903-95158fe2bd41"
ImageCore = "a09fc81d-aa75-5fe9-8630-4744c3626534"
Images = "916415d5-f1e6-5110-898d-aaa5f9f070e0"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
Luxor = "ae8d54c2-7ccd-5906-9d76-62fc9837b5bc"
MLDatasets = "eb30cadb-4394-5ae3-aed4-317e484a6458"
NPZ = "15e1cf62-19b3-5cfa-8e77-841668bca605"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
TableView = "40c74d1a-b44c-5b06-a7c1-6cbea58ea978"
WebIO = "0f1e0344-ec1d-5b48-a673-e5cf874b6c29"
